name: "pnpm Build"
description: "Run build script with pnpm"
author: "github-workflows"

inputs:
  script:
    description: "Script name to run"
    required: false
    default: "build"
  working-directory:
    description: "Directory containing package.json"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Build (pnpm run ${{ inputs.script }})
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -euo pipefail
        pnpm run ${{ inputs.script }}
